function V_I = podaj_IL2(t, t1, dose, pause)

    if(t >= t1 && t <= (t1 + dose) ...
        || t >= (t1 + dose + pause) && t <= (t1 + (2 * dose) + pause) ...
        || t >= (t1 + 1) && t <= (t1 + 1 + dose) ...
        || t >= (t1 + 1 + dose + pause) && t <= (t1 + 1 + (2 * dose) + pause) ...
        || t >= (t1 + 2) && t <= (t1 + 2 + dose) ...
        || t >= (t1 + 2 + dose + pause) && t <= (t1 + 2 + (2 * dose) + pause))
%         || t >= (t1 + 3) && t <= (t1 + 3 + dose) ...
%         || t >= (t1 + 3 + dose + pause) && t <= (t1 + 3 + (2 * dose) + pause) ...
%         || t >= (t1 + 4) && t <= (t1 + 4 + dose) ...
%         || t >= (t1 + 4 + dose + pause) && t <= (t1 + 4 + (2 * dose) + pause)...
%         || t >= (t1 + 5) && t <= (t1 + 5 + dose) ...
%         || t >= (t1 + 5 + dose + pause) && t <= (t1 + 5 + (2 * dose) + pause) ...
%         || t >= (t1 + 12) && t <= (t1 + 12 + dose) ...
%         || t >= (t1 + 12 + dose + pause) && t <= (t1 + 12 + (2 * dose) + pause) ...
%         || t >= (t1 + 13) && t <= (t1 + 13 + dose) ...
%         || t >= (t1 + 13 + dose + pause) && t <= (t1 + 13 + (2 * dose) + pause) ...
%         || t >= (t1 + 14) && t <= (t1 + 14 + dose) ...
%         || t >= (t1 + 14 + dose + pause) && t <= (t1 + 14 + (2 * dose) + pause) ... 
%         || t >= (t1 + 15) && t <= (t1 + 15 + dose) ...
%         || t >= (t1 + 15 + dose + pause) && t <= (t1 + 15 + (2 * dose) + pause) ...
%         || t >= (t1 + 16) && t <= (t1 + 16 + dose) ...
%         || t >= (t1 + 16 + dose + pause) && t <= (t1 + 16 + (2 * dose) + pause)...
%         || t >= (t1 + 72) && t <= (t1 + 72 + dose) ...
%         || t >= (t1 + 72 + dose + pause) && t <= (t1 + 72 + (2 * dose) + pause) ...
%         || t >= (t1 + 73) && t <= (t1 + 73 + dose) ...
%         || t >= (t1 + 73 + dose + pause) && t <= (t1 + 73 + (2 * dose) + pause) ...
%         || t >= (t1 + 74) && t <= (t1 + 74 + dose) ...
%         || t >= (t1 + 74 + dose + pause) && t <= (t1 + 74 + (2 * dose) + pause) ...
%         || t >= (t1 + 75) && t <= (t1 + 75 + dose) ...
%         || t >= (t1 + 75 + dose + pause) && t <= (t1 + 75 + (2 * dose) + pause) ...
%         || t >= (t1 + 76) && t <= (t1 + 76 + dose) ...
%         || t >= (t1 + 76 + dose + pause) && t <= (t1 + 76 + (2 * dose) + pause) ...
%         || t >= (t1 + 77) && t <= (t1 + 77 + dose) ...
%         || t >= (t1 + 77 + dose + pause) && t <= (t1 + 77 + (2 * dose) + pause) ...
%         || t >= (t1 + 78) && t <= (t1 + 78 + dose) ...
%         || t >= (t1 + 78 + dose + pause) && t <= (t1 + 78 + (2 * dose) + pause) ...
%         || t >= (t1 + 79) && t <= (t1 + 79 + dose) ...
%         || t >= (t1 + 79 + dose + pause) && t <= (t1 + 79 + (2 * dose) + pause) ...
%         || t >= (t1 + 80) && t <= (t1 + 80 + dose) ...
%         || t >= (t1 + 80 + dose + pause) && t <= (t1 + 80 + (2 * dose) + pause) ...
%         || t >= (t1 + 81) && t <= (t1 + 81 + dose) ...
%         || t >= (t1 + 81 + dose + pause) && t <= (t1 + 81 + (2 * dose) + pause) ...
%         || t >= (t1 + 82) && t <= (t1 + 82 + dose) ...
%         || t >= (t1 + 82 + dose + pause) && t <= (t1 + 82 + (2 * dose) + pause))
        
        V_I = 5e6;
        
    else
        
        V_I = 0;
    
    end
   
 end
