function V_M = podaj_cytostatyk(t, liczba_dni_w_cyklu, dawkowanie)

    if(t >= 0 && t <= dawkowanie || t >= liczba_dni_w_cyklu && t <= liczba_dni_w_cyklu + dawkowanie ...
        || t >= 2*liczba_dni_w_cyklu && t <= (2*liczba_dni_w_cyklu) + dawkowanie ...
        || t >= 3*liczba_dni_w_cyklu && t <= (3*liczba_dni_w_cyklu) + dawkowanie ...
        || t >= 4*liczba_dni_w_cyklu && t <= (4*liczba_dni_w_cyklu) + dawkowanie ...
        || t >= 5*liczba_dni_w_cyklu && t <= (5*liczba_dni_w_cyklu) + dawkowanie ...
        || t >= 6*liczba_dni_w_cyklu && t <= (6*liczba_dni_w_cyklu) + dawkowanie ...
        || t >= 7*liczba_dni_w_cyklu && t <= (7*liczba_dni_w_cyklu) + dawkowanie ...
        || t >= 8*liczba_dni_w_cyklu && t <= (8*liczba_dni_w_cyklu) + dawkowanie)
    
        V_M = 5;
    
    else
        
        V_M = 0;
    
    end
   
 end
