function V_I = podaj_IL2(t, t1, dose, pause)

    if(t >= t1 && t <= (t1 + dose) ...
        || t >= (t1 + dose + pause) && t <= (t1 + (2 * dose) + pause)...
        || t >= (t1 + (2 * dose) + (2 * pause)) && t <= (t1 + (3 * dose) + (2 * pause)) ...
        || t >= (t1 + (3 * dose) + (3 * pause)) && t <= (t1 + (4 * dose) + (3 * pause)) ...
        || t >= (t1 + (4 * dose) + (4 * pause)) && t <= (t1 + (5 * dose) + (4 * pause)) ...
        || t >= (t1 + (5 * dose) + (5 * pause)) && t <= (t1 + (6 * dose) + (5 * pause)))
%         || t >= (t1 + (6 * dose) + (6 * pause)) && t <= (t1 + (7 * dose) + (6 * pause)) ...
%         || t >= (t1 + (7 * dose) + (7 * pause)) && t <= (t1 + (8 * dose) + (7 * pause)) ...
%         || t >= (t1 + (8 * dose) + (8 * pause)) && t <= (t1 + (9 * dose) + (8 * pause)) ...
%         || t >= (t1 + (9 * dose) + (9 * pause)) && t <= (t1 + (10 * dose) + (9 * pause)) ...
%         || t >= (t1 + (10 * dose) + (10 * pause)) && t <= (t1 + (11 * dose) + (10 * pause)) ...
%         || t >= (t1 + (11* dose) + (11 * pause)) && t <= (t1 + (12 * dose) + (11 * pause)) ...
%         || t >= (t1 + (12 * dose) + (12 * pause)) && t <= (t1 + (13 * dose) + (12 * pause)) ...
%         || t >= (t1 + (13 * dose) + (13 * pause)) && t <= (t1 + (14 * dose) + (13 * pause)))
%         || t >= (t1 + (14 * dose) + (14 * pause)) && t <= (t1 + (15 * dose) + (14 * pause)) ...
%         || t >= (t1 + (15 * dose) + (15 * pause)) && t <= (t1 + (16 * dose) + (15 * pause)) ...
%         || t >= (t1 + (16 * dose) + (16 * pause)) && t <= (t1 + (17 * dose) + (16 * pause)) ...
%         || t >= (t1 + (17 * dose) + (17 * pause)) && t <= (t1 + (18 * dose) + (17 * pause)) ...
%         || t >= (t1 + (18 * dose) + (18 * pause)) && t <= (t1 + (19 * dose) + (18 * pause)) ...
%         || t >= (t1 + (19 * dose) + (19 * pause)) && t <= (t1 + (20 * dose) + (19 * pause)) ...
%         || t >= (t1 + (20* dose) + (20 * pause)) && t <= (t1 + (21 * dose) + (20 * pause)) ...
%         || t >= (t1 + (21 * dose) + (21 * pause)) && t <= (t1 + (22 * dose) + (21 * pause)) ...
%         || t >= (t1 + (22 * dose) + (22 * pause)) && t <= (t1 + (23 * dose) + (22 * pause)) ...
%         || t >= (t1 + (23 * dose) + (23 * pause)) && t <= (t1 + (24 * dose) + (23 * pause)))

        
        V_I = 5e6;
        
    else
        
        V_I = 0;
    
    end
   
 end
